### ISSUE TITLE
Softlock - Vault 5?

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#818] opened 2021-01-27 09:27 UTC
**Describe the bug**
Another softlock, this time without a rewind so creating a new issue. This time the game softlocked while resolving the effects of The Coin That Strays, played from Deeper Into The Vaults.

**What does it affect**
Card(s): The Coin That Strays?, Deeper Into The Vaults?
Deck(s): Vault 5

**To Reproduce**
1. Have Deeper Into The Vaults reveal and play The Coin That Strays.
2. After resolving damage and play from The Coin That Strays, the game softlocked.

**Screenshots**
<img width="1916" alt="coin that strays bug 1" src="https://user-images.githubusercontent.com/12156626/105970707-a9ac6180-6057-11eb-9256-daf42dde7084.png"> Should The Coin already be in the hero selected (Malichae in this case) play area?
<img width="1918" alt="coin that strays bug 2" src="https://user-images.githubusercontent.com/12156626/105970718-aca75200-6057-11eb-890d-68bb3c617172.png"> This is the Coin that Strays. Deeper into the Vaults and Gloomweaver were normal when large carded, nothing else was clickable.

**Logs**
[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/5879020/output_log.txt)

**Additional context**
Gargoyle in the game again, not sure if related to me other softlock issues as no rewind.

**Comment by NinjaMonkey1234** [comment] 2021-01-27 19:03
ENGINE DEBUG: GameController moved Prismatic Vision to Malichae's trash.
UIMoveCardAction, card = Prismatic Vision, from = Malichae's play area, to = Malichae's trash
Could not find card location for location Malichae/Trash

This is the last action i see before the system logs an exception. I'm not familiar enough with these logs to know for sure, but I'd imagine trying to move a card to a location the system can't find mind be problematic.

**Comment by LNBertolini** [comment] 2021-01-27 19:24
"Could not find card location for location [wherever]" is extremely common in the output_logs in general, and as far as I can tell not something to worry about. The problem here seems to be that Vault 5's artifacts fail to get rebuilt on reload, which causes the issue. Another probable duplicate of #787.

(If I had to speculate, the "could not find card location" is because the game is trying to decide where to draw the visual card, but of course because it doesn't actually draw cards in trashes it can't find where to put it.)

**Closed** 2021-01-30 17:16 UTC
Labels: duplicate
