### ISSUE TITLE
Spite & MSS Malichae

### ISSUE THREAD

**Issue by jkittycat** [SotMSteamMods/CauldronMods#1046] opened 2021-03-05 19:28 UTC
**Describe the bug**
Spite's PL626 Compound XI hits MSS Malichae twice whenever he uses his base power.

**What does it affect**
Card(s): Ministry of Strategic Science Malichae, PL626 Compound XI
Deck(s): Ministry of Strategic Science Malichae, Spite

**To Reproduce**
1. Wait for Spite to bring out PL626 Compound XI
2. Use MSS Malichae's base power

**Expected behavior**
Malichae to only get hit once for using a power.

**Screenshots**
N/A

**Logs**
N/A

**Additional context**
N/A

**Comment by wrhyme29** [comment] 2021-03-05 20:38
Wouldn't this be the correct behavior? His base power is being used (1) and then he is using the power on a card he is discarding (2). This would be similar behavior for Greatest Legacy using his power on himself to use another power, such as Motivational Charge

**Comment by cdallasanta** [comment] 2021-04-02 04:33
Completionist Guise shows the same behavior when using a second character's power off of his base.

**Comment by wrhyme29** [comment] 2021-04-02 15:52
Since it is confirmed to be the expected behavior, I will be closing this issue.

**Closed by wrhyme29** 2021-04-02 15:52 UTC
