### ISSUE TITLE
Dungeon of Terror: Underleveled with empty trash

### ISSUE THREAD

**Issue by NinjaMonkey1234** [SotMSteamMods/CauldronMods#956] opened 2021-02-19 14:14 UTC
**Describe the bug**
When Underleveled is out and the environment trash is empty, Underleveled does not provide a +1 damage bonus to hero targets.

**What does it affect**
Card(s): Underleveled
Deck(s): Dungeon of Terror

**To Reproduce**
1. Underleveled in play
2. Environment trash is empty

**Expected behavior**
Hero targets should receive a +1 damage bonus.

**Screenshots**
![image](https://user-images.githubusercontent.com/28448033/108514898-11864e80-728a-11eb-9458-a468bc321a72.png)

**Comment by wrhyme29** [comment] 2021-02-19 14:28
Closing, duplicate of #955

**Closed by wrhyme29** 2021-02-19 14:28 UTC
Labels: duplicate
