### ISSUE TITLE
Once Cauldron Heroes have Rewards, clicking rewind can sometimes irreparably freeze the game

### ISSUE THREAD

**Issue by mredgecase** [SotMSteamMods/CauldronMods#1070] opened 2021-03-08 03:24 UTC
**Describe the bug**
It's hard to tell - there have been multiplayer OA games with nothing but Cauldron heroes and plenty of rewinds that have been fine. This is the first time it's happened in single-player mode.  I think it has to do with having rewards under incapped Cauldron heroes. 

**What does it affect**
Everything. Click rewind, and then the game freezes, although you can still right-click things to see larger images. If you Main Menu out, you return to an all-black "turn taker name" screen. 

"clicking rewind after terminus' turn = freeze.txt" is an output log from single player. All the others are multiplayer. 

[clicking rewind after terminus' turn = freeze.txt](https://github.com/SotMSteamMods/CauldronMods/files/6098723/clicking.rewind.after.terminus.turn.freeze.txt)
[oblivaeon freeze after rewinding after bringing in sentinels.txt](https://github.com/SotMSteamMods/CauldronMods/files/6098736/oblivaeon.freeze.after.rewinding.after.bringing.in.sentinels.txt)
[oblivaeon goes to hell once 'plays redshift'.txt](https://github.com/SotMSteamMods/CauldronMods/files/6098747/oblivaeon.goes.to.hell.once.plays.redshift.txt)
[oblivaeon post-eot freeze w-cauldron heroes.txt](https://github.com/SotMSteamMods/CauldronMods/files/6098753/oblivaeon.post-eot.freeze.w-cauldron.heroes.txt)

![image](https://user-images.githubusercontent.com/78523123/110271250-9add9680-7f95-11eb-9a12-c7c09dc49d68.png)

**Comment by MSpekkio** [comment] 2021-03-08 13:34
Hello Edge,

I reviewed the logs and these look like known issues that are fixed in 0.4.1. Two from Starlight multicharacter, 1 knight multicharacter, and 1 from Pyre's Irradiated markers.  All three of these specific crashes were fixed in 0.4.1.

I think this issue can be closed.

**Comment by wrhyme29** [comment] 2021-03-08 15:31
I would like to find some way to more thoroughly test this to make sure it is resolved. However, in trying to recreate the issue on v0.4.1 I was unable to do so, so MSpekkio's thought seems to be on track.

Could you try to reproduce the freeze again now that you are on v0.4.1? Otherwise, we can close this issue

**Comment by wrhyme29** [comment] 2021-05-05 02:18
Closing this issue due to not occurring the current version

**Closed by wrhyme29** 2021-05-05 02:18 UTC
Labels: question
