### ISSUE TITLE
Malichae - High and Grand Djin UI bug.

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#73] opened 2020-11-19 19:47 UTC
![attached djin power bug](https://user-images.githubusercontent.com/12156626/99716321-f717bb80-2a75-11eb-9d12-09d36d74de60.png)

As seen in attached screenshot, when trying to select a power from an attached djin card, the UI is only displaying it as a small yellow box and thin green vertical line. It is clickable and usable though.

**Comment by LNBertolini** [comment] 2020-11-19 19:54
Duplicate of #69

**Closed by LNBertolini** 2020-11-19 19:54 UTC
