### ISSUE TITLE
St. Simeon's - Omnitron-X Defensive Blast softlock vs. invisible ghosts

### ISSUE THREAD

**Issue by LNBertolini** [SotMSteamMods/CauldronMods#757] opened 2021-01-16 06:24 UTC
**Describe the bug**
In a game vs. Screamachine in St. Simeon's Catacombs, using Omnitron-X's Defensive Blast causes the game to softlock. I am not actually sure what is causing this; the exception is somewhat uninformative.

The setup: Possessor and Terrible Presence are out, with Aqueducts as the room. Ricky G got all three Drummer cards out and was then was ejected. Swarming Protocol Cypher has a few face-down augments out. The other characters are Guise (incapped), Tango One 1929, and Xtreme Prime Wardens Tempest. Nothing else seems like it is possibly relevant.

I suspect, but do not know, that this is the result of a bad interaction between Defensive Blast/SelectTargetsAndDealMultipleInstancesOfDamage and the ghost-invisibility effect on Possessor.

**What does it affect**
Card(s): Defensive Blast and *something.*
Deck(s): Omnitron-X, possibly one of St. Simeon's Catacombs and ScreaMachine.

**To Reproduce**
Not sure. The first thing I would look at is:
1. Play Omni-X in St. Simeon's Catacombs
2. Get out Defensive Blast, any plating, and at least one invisible ghost.
3. Use Defiensive Blast's power.

**Expected behavior**
The game does not softlock.

**Logs**
Attached are a log of a full game, and a much shorter one from after exiting the program and reloading
[output_log-reload.txt](https://github.com/SotMSteamMods/CauldronMods/files/5823962/output_log-reload.txt)
.
[output_log-full.txt](https://github.com/SotMSteamMods/CauldronMods/files/5823961/output_log-full.txt)

**Comment by LNBertolini** [comment] 2021-01-16 06:40
I believe I have pretty good evidence for the 'invisible ghost' theory - later in the same game, once I had cleared out the spectral infestation, i was again able to use Defensive Blast with no issues. Renaming the issue appropriately.

**Comment by MSpekkio** [comment] 2021-01-25 02:01
I've replicated the issue in a test case and the exception is coming from SelectTargetsAndDealMultipleInstancesOfDamage in the base engine code.
I've pushed a branch with test code to replicate and fix the issue
https://github.com/SotMSteamMods/CauldronMods/tree/issue757-nre-with-dealmultipleinstancesofdamage

I'm not sure if there's a way for us to work around the problem.
Root cause is a call to FindCardsWhere without a CardSource to test visibility. Annotated function call below:
`IEnumerable<Card> targets = CardController.FindCardsWhere((Card c) => c.IsInPlayAndHasGameText && c.IsTarget, realCardsOnly: false, cardSource: null, ignoreBattleZone: false);`

which dispatches to GameController.FindCardsWhere which has this `(visibleToCard == null || IsCardVisibleToCardSource(c, visibleToCard)) `

I suspect this means we are stuck and need a fix from MigrantP.

**Comment by LNBertolini** [comment] 2021-03-05 21:35
For MigrantP: The branch has comments with more detail. [This](https://github.com/SotMSteamMods/CauldronMods/compare/issue757-nre-with-dealmultipleinstancesofdamage#diff-07bb48aab22f039297f4338e0d325f68b79a6683fe8df7c190b43eecf70087ecR274) is the diff.

**Comment by wrhyme29** [comment] 2021-03-06 17:01
Here's a save file loaded into omniX's power phase. when you use defensive blast, the softlock will occur

[omni-x_visibility.zip](https://github.com/SotMSteamMods/CauldronMods/files/6095735/omni-x_visibility.zip)

**Comment by MigrantP** [comment] 2021-04-16 17:33
That save file is from the start of the game, not Omnitron-X's turn.

**Comment by wrhyme29** [comment] 2021-04-16 21:27
Sorry about that - definitely grabbed the wrong thing last time. Here's a corrected one - I tested loading it in the test suite and it brought me to the right place.

Its loaded into Omnitron X's Power Phase. Just use the power on Defensive Blast and the softlock will occur.


[omniXInvisibilityBug.zip](https://github.com/SotMSteamMods/CauldronMods/files/6327946/omniXInvisibilityBug.zip)

**Comment by MigrantP** [comment] 2021-04-23 17:37
This will be fixed in the next update.

**Closed** 2021-05-01 20:01 UTC
Labels: confirmed bug
