### ISSUE TITLE
Stranger - Mark of Destruction

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#71] opened 2020-11-19 19:37 UTC
Since Mark of Destruction is a hero target, it is not visible as a target unless you click "Show all targets". This is a bit of a pain, as you often want to deal it damage. Not sure if this is actually fixable. I suppose it's like Absolute Zero wanting to hit himself.

**Comment by TopherGerkey** [comment] 2020-11-20 00:11
Necro's zombies are similar. This will primarily affect players who aren't familiar with how these decks work. It's not a bug per se, but it's awkward.

**Comment by Vilnor** [comment] 2020-11-26 18:51
I don't see any way to change this behavior.  Similar 'friendly targets you want to damage' like Unity's Cryobot work the same way.  Marking this engine limitation and closing.

**Closed by Vilnor** 2020-11-26 18:51 UTC
Labels: engine limitation
