### ISSUE TITLE
Hydra Tiamat Soft Lock - Link to Full Log included

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#591] opened 2020-12-22 22:07 UTC
**Describe the bug**
Hydra Tiamat softlocked at the start of her turn and I have no idea why. 

**What does it affect**
Card(s): 
Deck(s): Hydra Tiamat

**To Reproduce**
I've included the complete log below, but it was Hydra Tiamat vs AH Stuntman, PW AA, The Stranger, KNYFE, and Starlight Genesis in Blackwood Forest. All of the first three heads were down and this would have been the turn the other three came into play. 

**Expected behavior**

**Screenshots**

**Additional context**
https://pastebin.com/RQHUqzbw

**Comment by LNBertolini** [comment] 2020-12-23 00:26
Duplicate of #545

**Closed by LNBertolini** 2020-12-23 00:26 UTC
