### ISSUE TITLE
Tango One - Perfect Focus decision prompt

### ISSUE THREAD

**Issue by LNBertolini** [SotMSteamMods/CauldronMods#91] opened 2020-11-19 22:52 UTC
When playing Perfect Focus, you are given a yes-no decision with the description "Do you want to play Perfect Focus?" Selecting "yes" lets you play the followup card as normal. However, it is typical in these cases to just let the player play a second card using the normal interface, and pick the "skip" button if they don't want to. (Compare Tachyon's Fleet of Foot/Lightning Reflexes or Wraith's Impromptu Invention)

**Comment by breenyoung** [comment] 2020-11-19 23:28
Duplicate of #82

**Comment by LNBertolini** [comment] 2020-11-19 23:36
Close, but not quite - that issue is on the matter of what the prompt tells you the decision will do, this one is on the matter of the prompt existing at all.

**Closed** 2020-11-24 06:52 UTC
Labels: base-game-conformity
