### ISSUE TITLE
Hydra Tiamat Lock

### ISSUE THREAD

**Issue by jkittycat** [SotMSteamMods/CauldronMods#749] opened 2021-01-13 02:58 UTC
**Describe the bug**
Killing Hydra Tiamat's Mouth of the Inferno last without flipping it causes a lock - the game stops at the start of the villain turn. 

**What does it affect**
Card(s): Tiamat, Mouth of the Inferno
Deck(s): Hydra Tiamat

**To Reproduce**
1. Kill all hydra heads without killing Inferno, including Earth and Wind
2. Kill Inferno, thus leaving all heads incapacitated
3. Game gets stuck at start of villain turn

**Expected behavior**
Either a win or Decay coming into play.

**Screenshots**
![20210112203534_1](https://user-images.githubusercontent.com/77370875/104400875-b9d12680-5518-11eb-87ae-a9f613b191dd.jpg)

**Logs**
[hydraLock.zip](https://github.com/SotMSteamMods/CauldronMods/files/5806110/hydraLock.zip)

**Additional context**
Could still access the menu & look at the visible cards in play, but not zoom on the heroes.

**Comment by jkittycat** [comment] 2021-01-13 02:59
Additional note - just tried going back to menu, game crashed instead.

**Comment by wrhyme29** [comment] 2021-01-13 22:30
Looks like an infinite loop is happening - more investigation is needed

![image](https://user-images.githubusercontent.com/32969943/104517987-9cee2f00-55bc-11eb-9d40-153480ef0d85.png)

**Comment by LNBertolini** [comment] 2021-01-14 05:36
This is a duplicate of #715; it has already been fixed for the next release.

**Closed by LNBertolini** 2021-01-14 05:36 UTC
