### ISSUE TITLE
Malichae - Grand Somael (Cosmetic Issue)

### ISSUE THREAD

**Issue by ayoung1972** [SotMSteamMods/CauldronMods#300] opened 2020-11-29 23:30 UTC
**Describe the bug**
(Cosmetic) Grand Somael has a markup typo for the bolding on the POWER. Text currently states "B} POWER"  Should be "**POWER**"

**What does it affect**
Card(s): Grand Somael
Deck(s): Malichae

**To Reproduce**
1. Right Click the Grand Somael Card. 

**Expected behavior**
Word POWER Should be Bolded.

**Screenshots***

![GrandSomael](https://user-images.githubusercontent.com/74318975/100556517-4c737a00-3279-11eb-967f-90c5af352b0b.jpg)

**Comment by LNBertolini** [comment] 2020-11-30 01:01
Duplicate of #250

**Closed by LNBertolini** 2020-11-30 01:01 UTC
