### ISSUE TITLE
Impulse's Local Microgravity does not block damage from Nightlore Citadel's Gravity Fluctuation 

### ISSUE THREAD

**Issue by mredgecase** [SotMSteamMods/CauldronMods#1526] opened 2021-11-04 03:59 UTC
**Describe the bug**
Impact takes damage from Gravity Fluctuation [1] despite Local Microgravity [2] being in play. 

[1] "When this card enters play, it deals each hero with more than 3 cards in their hand 2 irreducible melee damage. "
[2] "The first time Impact would be dealt damage each environment turn, prevent that damage."
 
**What does it affect**
Card(s): Local Microgravity, Gravity Fluctuation
Deck(s): Impact; Nightlore Citadel 

**To Reproduce**
1. Use this setup
Impact in the Nightlore Citadel 

2. Play these cards to setup
Ensure Local Microgravity is in play and that Impacy has 4+ cards in hand

3. Play the problem card
Have Gravity Fluctuation enter play

Impact gets hit

**Expected behavior**
Local Microgravity should have blocked the damage from Gravity Fluctuation

**Comment by wrhyme29** [comment] 2021-11-26 06:02
Was Local Microgravity played during the environment turn? The prevention only occurs in the environment turn, so if it was Gravity Fluctuation was played out of turn, that would cause Local Microgravity not to kick in

**Comment by wrhyme29** [comment] 2021-11-26 06:07
I have confirmed through testing that Local Microgravity does prevent the damage from Gravity Fluctuation when it is the environment turn, but not if it is a non-environment turn, as intended. Unless you tell me otherwise, I will close this issue.

**Closed** 2021-12-01 04:42 UTC
Labels: could not replicate
