### ISSUE TITLE
Blackwood Forest - Mirror Wraith Being Lost in the Forest

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#185] opened 2020-11-22 18:47 UTC
**Describe the bug**
Mirror Wraith lost it's tags in a game with Akash'Thriya where it mimicked a Primordial Seed. It was one during the environment turn, but I didn't see when it was lost, though it did maintain the same amount of health. It was then that I realized it is no longer able to targeted, despite having health.

**What does it affect**
Card(s): Mirror Wraith
Deck(s): Blackwood Forest

**To Reproduce**
A game with Akash'Thriya and Blackwood Forest may have something to do with it, but it may just be Mirror Wraith. 

**Expected behavior**
To have the Mirror Wraith still function as a seed - and be in play. 

**Screenshots**

**Additional context**

**Comment by breenyoung** [comment] 2020-11-24 12:21
Please recheck this next new build as #183 is fixed in it and this may be related

**Comment by breenyoung** [comment] 2020-11-27 03:04
Tried to reproduce this since implementing #183 and was unsuccessful.  Had MW clone a primordial seed and he was targetable for many rounds until he was ultimately destroyed.  Marking this as unreproducible for now.

**Closed** 2020-12-13 22:42 UTC
Labels: could not replicate
