### ISSUE TITLE
"Thievery" Bug in Chasm of Thousand Nights

### ISSUE THREAD

**Issue by Hankroyd** [SotMSteamMods/CauldronMods#931] opened 2021-02-11 19:42 UTC
**Describe the bug**
'Thievery' force the discard even when the damage is prevented.
It cause weird interaction with redirection (If the redirected target has no card, then the original target must discard)

**What does it affect**
Card(s): Thievery
Deck(s): Chasm of Thousand Night

**To Reproduce**
1. 5 players game, put Naturalist anywhere but 5th
2. Indomitable Force, Rhinoceros Form (Naturalist must have at most 4 cards in hand)
3. A target with 'Thievery' that could damage all heroes for 1 (Gul for example, when it destroys a target)
4. Damage are redirected to Naturalist and prevented, the naturalist still has to discard a card each time.
5. When the damage on the 5th target is redirected, the Naturalist doesn't have any card, so the 5th hero has to discard a card instead.

**Expected behavior**
No damage=No discard

**Additional context**
Above is how I triggered the problem, but I guess any damage prevention on the environment target will trigger it.

**Comment by LNBertolini** [comment] 2021-02-11 19:45
Duplicate of #821

**Closed by LNBertolini** 2021-02-11 19:45 UTC
